### ISSUE TITLE
Dependency Injection for controller instances

### ISSUE THREAD

**Issue by buehler** [smartive/giuseppe#77]
since controllers are instantiated, it would be cool to have some sort of a dependency injection (constructor injection?) to provide certain things via DI.

an example could be an instance of an elasticsearch client, or some other injected things

**Comment by remojansen** [comment]
Hi guys, 

I'm the author of InversifyJS. 

I'm planning a breaking change for InversifyJS. I would really appreciate your feedback because the breaking change is mostly to improve node.js development thanks to async / await support which is going to be released in TypeScript 2.1 in a couple of weeks.

Please review https://github.com/inversify/InversifyJS/issues/404

Thanks!

**Comment by buehler** [comment]
@remojansen 

Thanks for the notification :-) I'm gonna read it through

Cheers
